---
- name: Check if database root password file exists
  stat:
    path: "{{database_root_password_file_path}}"
  register: database_root_password_file

- name: Generate database root password
  shell: "openssl rand -hex {{secret_size}}"
  register: generated_database_root_password
  when: database_root_password_file.stat.exists == false

- name: Setup database root password
  copy:
    dest: "{{database_root_password_file_path}}"
    content: "{{generated_database_root_password.stdout}}"
  when: generated_database_root_password.changed
