---
- name: Check if database user password file exists
  stat:
    path: "{{database_user_password_file_path}}"
  register: database_user_password_file

- name: Generate database user password
  shell: "openssl rand -hex {{secret_size}}"
  register: generated_database_user_password
  when: database_user_password_file.stat.exists == false

- name: Setup database user password
  copy:
    dest: "{{database_user_password_file_path}}"
    content: "{{generated_database_user_password.stdout}}"
  when: generated_database_user_password.changed
