---
- name: Create systemd unit file
  template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/{{service_name}}.service"
    owner: root
    group: root
    mode: 0644
  register: systemd_service

- name: Reload systemd
  command: systemctl daemon-reload
  when: >
    systemd_service.changed

- name: Restart service (on changes)
  service:
    name: "{{service_name}}"
    state: restarted
    enabled: yes
  when: systemd_service.changed
    or dockerimage.changed
    or db_dockerimage.changed

- name: Start service (if not started)
  service:
    name: "{{service_name}}"
    state: started
    enabled: yes
