Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.network "private_network", ip: "192.168.33.83"

  config.vm.provider "virtualbox" do |v|
    v.name = "ansible_nextcloud"
    v.memory = 2048
    v.cpus = 2
  end
end
